### ISSUE TITLE
can cones have more than one origin?

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/mmp-frontend#125]
cones are calculated backend side [here](https://github.com/acdh-oeaw/mmp/blob/e331be01698ddd0af7e552bb86d8e074084dc178/archiv/models.py#L1631) from `Stelle.text.ort` - where `ort` allows multiple places.

the frontend currently always takes only the first place, which is fine in most cases i guess, but in theory the cone could have been calculated with more than one place origins. do we have to account for that?

EDIT: also a cone is allowed to be associated with multiple passages

**Comment by csae8092** [comment]
* yes. cones can have more origins if the text related to the stelle, related to the spatial coverage object is related to more than one places with coordinates
* and also spatial coverage can be related to n stellen (https://github.com/acdh-oeaw/mmp/blob/e331be01698ddd0af7e552bb86d8e074084dc178/archiv/models.py#L1519) (which I opposed several times because it makes no sense at all)

**Comment by stefanprobst** [comment]
thanks.

example of cones with multiple origins:

- https://mmp.acdh-dev.oeaw.ac.at/api/cones/108/ has a relation to "Vita Anskarii" with Bremen and Hamburg

example of cones with multiple passages, which each have multiple places:

- https://mmp.acdh-dev.oeaw.ac.at/api/cones/109/ has 14 relations to "Vita Anskarii", which links to Bremen and Hamburg (should these be deduplicated?)
- https://mmp.acdh-dev.oeaw.ac.at/api/cones/114/ has 16 relations to "Vita Anskarii", which links to Bremen and Hamburg
